// packages/navigation-vue/src/utils/Popup.tsx
import {
  type Component,
  Transition,
  type TransitionProps,
  createApp,
  ref,
} from 'vue'

/**
 * 动态弹出视图方法
 *
 * ```ts
 * const [show, close] = Popup();
 *
 * show(
 *   <button
 *     onClick={async () => {
 *       await close();
 *       console.log("leaved.");
 *     }}
 *   >
 *     close
 *   </button>
 * );
 * ```
 *
 * @param options 配置对象，同 Transition 属性
 */
export const Popup = (options?: TransitionProps & { root?: Element }) => {
  // create document
  const container = document.createElement('div')
  ;(options?.root ?? document.body).appendChild(container)

  const isShowRef = ref(false)
  const componentRef = ref<Component>()

  const hiddenModal = () => {
    isShowRef.value = false
    componentRef.value = undefined
  }

  // 外部调用 promise resolve
  let __resolve: () => void
  const close = () => {
    return new Promise<void>((resolve) => {
      __resolve = () => resolve()
      hiddenModal()
    })
  }

  const app = createApp(() => (
    <Transition
      {...options}
      onAfterEnter={(el) => {
        if (options?.onAfterEnter) {
          if (typeof options.onAfterEnter === 'function') {
            options.onAfterEnter(el)
          } else {
            options.onAfterEnter.forEach((f) => f(el))
          }
        }
        __show_resolve?.()
      }}
      // overwrite onAfterLeave
      onAfterLeave={(el) => {
        if (options?.onAfterLeave) {
          if (typeof options.onAfterLeave === 'function') {
            options.onAfterLeave(el)
          } else {
            options.onAfterLeave.forEach((f) => f(el))
          }
        }

        app.unmount()
        document.body.removeChild(container)
        __resolve?.()
      }}
    >
      {isShowRef.value ? componentRef.value : null}
    </Transition>
  ))

  let __show_resolve: () => void
  const show = (component: Component) => {
    return new Promise<void>((resolve) => {
      __show_resolve = resolve
      app.mount(container)
      componentRef.value = component
      isShowRef.value = true
    })
  }

  return [show, close] as const
}

// packages/navigation-react/src/utils/Popup.tsx
import { type ReactNode, useEffect, useRef } from 'react'
import { createRoot, type Root } from 'react-dom/client'

interface TransitionCallbacks {
  onEnter?: (el: Element, done: () => void) => void
  onLeave?: (el: Element, done: () => void) => void
  root?: Element
}

/**
 * 动态弹出视图方法 (React 版本)
 *
 * ```tsx
 * const [show, close] = Popup({
 *   onEnter(el, done) {
 *     animate(el, { opacity: [0, 1], onComplete: done })
 *   },
 *   onLeave(el, done) {
 *     animate(el, { opacity: [1, 0], onComplete: done })
 *   }
 * })
 *
 * show(<div>Hello</div>)
 * // later...
 * await close()
 * ```
 */
export const Popup = (options?: TransitionCallbacks) => {
  // create container
  const container = document.createElement('div')
  ;(options?.root ?? document.body).appendChild(container)

  let root: Root | null = null
  let currentElement: Element | null = null
  let closeResolve: (() => void) | null = null
  let showResolve: (() => void) | null = null
  let enterCalled = false

  const close = (): Promise<void> => {
    return new Promise((resolve) => {
      closeResolve = () => {
        // cleanup
        root?.unmount()
        root = null
        container.parentNode?.removeChild(container)
        resolve()
      }

      if (currentElement && options?.onLeave) {
        options.onLeave(currentElement, () => {
          closeResolve?.()
        })
      } else {
        closeResolve?.()
      }
    })
  }

  const show = (content: ReactNode): Promise<void> => {
    return new Promise((resolve) => {
      showResolve = resolve
      enterCalled = false

      const PopupContent = () => {
        const ref = useRef<HTMLDivElement>(null)
        
        useEffect(() => {
          if (ref.current && !enterCalled) {
            enterCalled = true
            currentElement = ref.current
            if (options?.onEnter) {
              options.onEnter(ref.current, () => {
                showResolve?.()
              })
            } else {
              showResolve?.()
            }
          }
        }, [])

        return <div ref={ref}>{content}</div>
      }

      root = createRoot(container)
      root.render(<PopupContent />)
    })
  }

  return [show, close] as const
}
