// packages/navigation-react/src/components/Loading/index.tsx
import { type FC } from 'react'
import { animate } from 'animejs'
import { enableBodyPointerEvents, disableBodyPointerEvents } from '@0x30/navigation-core'
import { push, back } from '../../navigation'
import { useLeaveBefore, useQuietPage } from '../../hooks'
import { Popup } from '../../utils'
import styles from './index.module.scss'

// 内置 SVG 图标
const LoadingSvg: FC = () => (
  <svg viewBox="0 0 100 100" className={styles.spinner}>
    <circle cx="50" cy="50" r="40" stroke="currentColor" strokeWidth="8" fill="none" strokeLinecap="round" />
  </svg>
)

const SuccessSvg: FC = () => (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <polyline points="20 6 9 17 4 12" />
  </svg>
)

const ErrorSvg: FC = () => (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <line x1="18" y1="6" x2="6" y2="18" />
    <line x1="6" y1="6" x2="18" y2="18" />
  </svg>
)

/**
 * 0: 展示 loading
 * 1: 展示 success
 * 2: 展示 error
 * 3: 立即隐藏
 */
type Status = 0 | 1 | 2 | 3

interface LoadingConfig {
  successImg?: string
  errorImg?: string
  loadingImg?: string
  closeTimeout?: number
}

let config: LoadingConfig = {
  closeTimeout: 1500,
}

export const setLoadingConfig = (newConfig: LoadingConfig) => {
  config = { ...config, ...newConfig }
}

// 全局状态管理
let currentStatus: Status | undefined = undefined
let currentMessage: string | undefined = undefined
let closePopup: (() => Promise<void>) | undefined = undefined
let isShowLoading = false
let closeLoadingTimer: number | undefined = undefined

const setStatus = (status: Status) => {
  currentStatus = status

  if (status === 0) {
    disableBodyPointerEvents()
  } else {
    enableBodyPointerEvents()
  }
}

/**
 * Loading 实例接口 - 用于控制 loading 的状态和内容
 */
export interface LoadingInstance {
  /** 更新 loading 消息 */
  setMessage: (message: string) => void
  /** 切换为成功状态并自动关闭 */
  success: (message?: string, duration?: number) => void
  /** 切换为失败状态并自动关闭 */
  error: (message?: string, duration?: number) => void
  /** 立即隐藏 */
  hide: () => void
}

/**
 * Loading 页面组件 - 用于阻止用户返回
 */
const LoadingPage: FC = () => {
  // 阻止返回，只有 isShowLoading 为 false 时才允许
  useLeaveBefore(() => isShowLoading === false)
  // 静默页面，不触发其他页面的生命周期
  useQuietPage()
  
  return <div />
}

/**
 * Loading UI 组件 - Popup 内容
 */
const LoadingUI: FC = () => {
  const renderIcon = () => {
    switch (currentStatus) {
      case 0:
        return config.loadingImg ? <img src={config.loadingImg} alt="" /> : <LoadingSvg />
      case 1:
        return config.successImg ? <img src={config.successImg} alt="" /> : <SuccessSvg />
      case 2:
        return config.errorImg ? <img src={config.errorImg} alt="" /> : <ErrorSvg />
      default:
        return null
    }
  }

  return (
    <div className={styles.body}>
      <div className={styles.main}>
        <div className={styles.icon}>{renderIcon()}</div>
        {currentMessage && <span>{currentMessage}</span>}
      </div>
    </div>
  )
}

/**
 * 显示 Loading UI Popup
 */
const showLoadingPopup = async () => {
  // 如果已经有 popup 在显示，不重复创建
  if (closePopup !== undefined) return

  const [show, close] = Popup({
    onLeave(el, done) {
      const mainEl = el.querySelector(`.${styles.main}`)
      if (mainEl) {
        animate(mainEl, {
          opacity: [1, 0],
          duration: 200,
          ease: 'outExpo',
          onComplete: done,
        })
      } else {
        done()
      }
    },
  })

  closePopup = async () => {
    closePopup = undefined
    await close()
  }

  await show(<LoadingUI />)
}

/**
 * 创建一个 Loading 实例
 */
const createLoadingInstance = (): LoadingInstance => {
  return {
    setMessage: (message: string) => {
      currentMessage = message
    },
    success: (message?: string, duration?: number) => {
      internalShowLoading(1, message, duration)
    },
    error: (message?: string, duration?: number) => {
      internalShowLoading(2, message, duration)
    },
    hide: () => {
      internalShowLoading(3)
    },
  }
}

/**
 * 内部展示 loading 方法
 */
const internalShowLoading = async (status: Status, message?: string, duration?: number) => {
  window.clearTimeout(closeLoadingTimer)

  if (status === 0) {
    isShowLoading = true
    await push(<LoadingPage />)
  } else {
    if (isShowLoading) {
      isShowLoading = false
      await back()
    }
  }

  // 设置状态
  setStatus(status)
  currentMessage = message
  await showLoadingPopup()

  if (status === 0) return

  if (status === 3) {
    closeLoadingTimer = window.setTimeout(() => {
      closePopup?.()
    }, 150)
  } else {
    closeLoadingTimer = window.setTimeout(() => {
      closePopup?.()
    }, duration ?? config.closeTimeout)
  }
}

/**
 * 显示 Loading
 * @param message 可选的提示消息
 * @returns LoadingInstance 可用于后续控制 loading 状态
 */
export const showLoading = async (message?: string): Promise<LoadingInstance> => {
  await internalShowLoading(0, message)
  return createLoadingInstance()
}

/**
 * 隐藏 Loading
 */
export const hideLoading = async () => {
  await internalShowLoading(3)
}

/**
 * 显示成功提示
 * @param message 可选的提示消息
 * @param duration 可选的显示时长（毫秒）
 */
export const showSuccess = async (message?: string, duration?: number) => {
  await internalShowLoading(1, message, duration)
}

/**
 * 显示失败提示
 * @param message 可选的提示消息
 * @param duration 可选的显示时长（毫秒）
 */
export const showError = async (message?: string, duration?: number) => {
  await internalShowLoading(2, message, duration)
}

/**
 * 使用 Loading 的 Hook
 */
export const useLoading = () => {
  return {
    show: showLoading,
    hide: hideLoading,
    success: showSuccess,
    error: showError,
  }
}

// packages/layout/src/components/Loading/index.tsx
import {
  useQuietPage,
  back,
  push,
  useLeaveBefore,
  enableBodyPointerEvents,
  disableBodyPointerEvents,
} from '@0x30/vue-navigation'
import { defineComponent, ref } from 'vue'

import styles from './index.module.scss'
import { Popup } from '../../util/Popup'

import loadingImg from './imgs/loading.svg'
import errorImg from './imgs/error.svg'
import successImg from './imgs/success.svg'
import { animate } from 'animejs'

let customLoadingImg: string | undefined = undefined
let customErrorImg: string | undefined = undefined
let customSuccessImg: string | undefined = undefined
let autoCloseTimeout = 1500

/**
 * 配置loading的配置
 * @param param0
 */
const setLoadingConfig = ({
  successImg,
  failedImg,
  loadingImg,
  closeTimeout,
}: {
  /**
   * 成功的图片
   */
  successImg?: string
  /**
   * 失败的图片
   */
  failedImg?: string
  /**
   * 加载的图片
   */
  loadingImg?: string
  /**
   * 自动关闭的时间 ms 默认1500ms
   */
  closeTimeout?: number
}) => {
  loadingImg && (customLoadingImg = loadingImg)
  failedImg && (customErrorImg = failedImg)
  successImg && (customSuccessImg = successImg)
  closeTimeout !== undefined && (autoCloseTimeout = closeTimeout)
}

/**
 * 0: 展示 loading toast
 * 1: 展示 success toast
 * 2: 展示 failed toast
 * 3: 立即隐藏
 */
type Status = 0 | 1 | 2 | 3

const statusRef = ref<Status>()
const messageRef = ref<string>()
const closeRef = ref<() => Promise<void>>()

const imageRef = ref<string>()

const setStatus = (status: Status) => {
  statusRef.value = status

  if (status === 0) {
    disableBodyPointerEvents()
  } else {
    enableBodyPointerEvents()
  }

  if (status === 0) imageRef.value = customLoadingImg ?? loadingImg
  if (status === 1) imageRef.value = customSuccessImg ?? successImg
  if (status === 2) imageRef.value = customErrorImg ?? errorImg
}

const Component = defineComponent({
  name: 'LoadingView',
  setup: () => {
    return () => (
      <div class={styles.body}>
        <div class={styles.main}>
          {imageRef.value ? <img src={imageRef.value} /> : null}
          {messageRef.value ? <span>{messageRef.value}</span> : null}
        </div>
      </div>
    )
  },
})

const Loading = defineComponent(() => {
  useLeaveBefore(() => isShowLoading === false)
  useQuietPage()
  return () => <div />
})

const showLoadingComponent = async () => {
  /// 如果当前为展示 loading 组件 popup
  if (closeRef.value !== undefined) return

  const [show, close] = Popup({
    onLeave(el, onComplete) {
      animate(el.querySelector(`.${styles.main}`)!, {
        duration: 200,
        opacity: [1, 0],
        ease: 'outExpo',
        onComplete,
      })
    },
  })
  closeRef.value = async () => {
    closeRef.value = undefined
    await close()
  }

  await show(<Component />)
}

let closeLoadingTimer: number | undefined = undefined
let isShowLoading = false
/**
 * 展示 loading 页面
 * @param type
 * 0: 展示 loading toast
 * 1: 展示 success toast
 * 2: 展示 failed toast
 * 3: 立即隐藏
 * @param message
 */
const showLoading = async (status: Status, message?: string) => {
  window.clearTimeout(closeLoadingTimer)

  if (status === 0) {
    isShowLoading = true
    await push(<Loading />)
  } else {
    if (isShowLoading) {
      isShowLoading = false
      await back()
    }
  }

  /// 状态 ref
  setStatus(status)
  messageRef.value = message
  await showLoadingComponent()

  if (status === 0) return

  if (status === 3) {
    closeLoadingTimer = window.setTimeout(() => {
      closeRef.value?.()
    }, 150)
  } else {
    closeLoadingTimer = window.setTimeout(() => {
      closeRef.value?.()
    }, autoCloseTimeout)
  }
}

export { showLoading, setLoadingConfig }
