// examples/react-demo/src/main.tsx
import { createRoot } from 'react-dom/client'
import { 
  initNavigation, 
  push, 
  LoadingContainer, 
  ToastContainer 
} from '@0x30/navigation-react'
import Home from './views/Home'
import './styles/global.scss'

// 初始化导航
initNavigation()

// 渲染全局组件容器（Loading、Toast）
const globalContainer = document.createElement('div')
globalContainer.id = 'global-components'
document.body.appendChild(globalContainer)

const GlobalComponents = () => (
  <>
    <LoadingContainer />
    <ToastContainer />
  </>
)

createRoot(globalContainer).render(<GlobalComponents />)

// 推入首页
push(<Home />)

// examples/vue-demo/src/main.tsx
import { createApp, defineComponent } from 'vue'
import { push, LoadingContainer, ToastContainer } from '@0x30/navigation-vue'
import Home from './views/Home'
import './styles/global.scss'

// 创建全局组件容器
const GlobalComponents = defineComponent({
  name: 'GlobalComponents',
  setup: () => () => (
    <>
      <LoadingContainer />
      <ToastContainer />
    </>
  ),
})

// 渲染全局组件
const globalContainer = document.createElement('div')
globalContainer.id = 'global-components'
document.body.appendChild(globalContainer)
createApp(GlobalComponents).mount(globalContainer)

// 推入首页（第一次 push 会自动初始化）
push(<Home />)
